### ISSUE TITLE
Saving graph model neural network doesn't work 

### ISSUE THREAD

**Issue by kirill-pinigin** [tiny-dnn/tiny-dnn#674] opened 2017-04-28 19:34 UTC
I can't save my pre-trained  graph model net to binary or json format.
```cpp
int main ()
{
    network<graph>    net;
    layers::input     in1(2);
    layers::input     in2(2);
    layers::concat    concat(2, 2);
    layers::fc        fc(4, 2);
    activation::relu  r();
    adagrad opt;

    (in1, in2) << concat;
    concat << fc;
    construct_graph(net, { &in1, &in2 }, { &fc });

    // 2training data, each data type is tensor_t and shape is [2x2]
    //
    //                        1st data for in1       2nd data for in1
    //                              |                      |
    //                              |   1st data for in2   |   2nd data for in2
    //                              |         |            |         |
    std::vector<tensor_t> data{ { { 1, 0 }, { 3, 2 } },{ { 0, 2 }, { 1, 1 } } };
    std::vector<tensor_t> out { {           { 2, 5 } },{           { 3, 1 } } };

    net.fit<mse>(opt, data, out, 1, 1);

     net.save("/home/kirill/my-network.txt");

     network<graph>    net2;
     net2.load("/home/kirill/my-network.txt");

return 0;
}
```

Thrown exception!
```cpp
 const std::string &type_name(std::type_index index) const {
    if (type_names_.find(index) == type_names_.end()) {
      throw nn_error("Typename is not registered");
    }
    return type_names_.at(index);
  }
```

**Comment by Randl** [comment] 2017-04-30 08:10
`(in1, in2) << concat;` is invalid until https://github.com/tiny-dnn/tiny-dnn/pull/662 is merged

**Comment by edgarriba** [comment] 2017-04-30 22:55
@kirill-pinigin could you check again?

**Comment by kirill-pinigin** [comment] 2017-05-02 04:08
Спасибо большое)) а долго ждать данного мерджа? 30.04.2017, 11:11, "Evgeniy Zheltonozhskiy" <notifications@github.com>:(in1, in2) << concat; is invalid until #662 is merged

**Comment by kirill-pinigin** [comment] 2017-05-02 07:00
unfortunately, same exception has been thrown.  In both cases of usage  MSVC compiler  and g++!

**Comment by edgarriba** [comment] 2017-05-02 16:34
ping @karandesai-96

**Comment by kirill-pinigin** [comment] 2017-05-03 02:40
edgarriba, I can,t understand . What are  you mean?  I 've cloned karandesai-96 branch tiny-dnn  and built, but I  have same result and same exception.

**Comment by shivak7** [comment] 2017-05-05 23:07
I am noticing the same issue with my code as well. Saving graph networks after training still leads to the same exception error with the latest version.

**Comment by karandesai-96** [comment] 2017-05-06 03:57
I will try to reproduce this bug and get back here once I find something interesting.

**Comment by beru** [comment] 2017-05-06 04:01
Serialization of `average_unpooling_layer`, `deconvolutional_layer`, `input_layer`, `quantized_convolutional_layer`, `quantized_deconvolutional_layer`, `quantized_fully_connected_layer` layers are still not supported yet.

**Comment by karandesai-96** [comment] 2017-05-06 04:02
Oh I didn't know about input layer.

**Comment by shivak7** [comment] 2017-05-06 04:36
Is there a temporary makeshift way for saving and loading trained weights of graph networks for now?

**Comment by beru** [comment] 2017-05-06 04:58
@shivak7 If you have the source code of graph networks, you don't need to load it from a file since you can construct the network.

You can load and save weights with
```cpp
template <typename NetType, typename Char, typename CharTraits>
std::basic_ostream<Char, CharTraits> &operator<<(
  std::basic_ostream<Char, CharTraits> &os, const network<NetType> &n) {
  n.save(os);
  return os;
}

template <typename NetType, typename Char, typename CharTraits>
std::basic_istream<Char, CharTraits> &operator>>(
  std::basic_istream<Char, CharTraits> &os, network<NetType> &n) {
  n.load(os);
  return os;
}
```
routines inside `tiny_dnn/network.h` file.

**Closed** 2017-05-11 11:42 UTC
Labels: question

**Comment by parasag** [comment] 2017-11-21 14:13
I get the same Exception, 'Typename is not registered'. 
Issue is closed, Is this fixed?

**Comment by beru** [comment] 2017-11-25 03:56
@parasag If the problem persists at your side, please post a minimum working example that reproduces the problem so that other people can verify the cause.
