### ISSUE TITLE
Need help with tiny-dnn on Android

### ISSUE THREAD

**Issue by ameld** [tiny-dnn/tiny-dnn#334] opened 2016-10-08 14:10 UTC
Hello I'm doing a small project with tiny-dnn on Android. I want to do a classification for a image of the 
number eight with the MNIST model. The project compiles and it runs but after i call the native code i get an Error : "A/libc: Fatal signal 8 (SIGFPE), code -6, fault addr 0x5c33 in tid 23603 (igital.tinytest)"
[TinyDnnTesting](https://github.com/ameld/TinyDnnTesting)
Here is my small Project and the Data i use with the Net_model of MNIST, can someone help me or give me a hint what the problem is or how to solve it.

**Comment by zhangqianhui** [comment] 2016-10-09 01:52
I can success in compiling new version! But don't test the model.You can describe your work detailed

**Comment by Randl** [comment] 2017-02-10 10:16
@ameld Can you retry with latest version and confirm the issue is still present?

**Comment by Randl** [comment] 2017-02-18 08:58
No answer for more than a week. Closing

**Closed by Randl** 2017-02-18 08:58 UTC
Labels: support, Wait for reply
