### ISSUE TITLE
why not consider using std:move/move constructor to enhance performance ？

### ISSUE THREAD

**Issue by liwangqian** [tiny-dnn/tiny-dnn#523] opened 2017-01-18 14:36 UTC

**Comment by Randl** [comment] 2017-01-18 15:41
Where exactly?

**Comment by liwangqian** [comment] 2017-01-25 13:05
for example, the vector return from lossfunction and activation_function:
`
static vec_t df(const vec_t& y, const vec_t& t){
    vec_t d(t.size());
    ...;
    return d;
}
`
using

**Comment by nyanp** [comment] 2017-01-28 01:49
@liwangqian 
In this case, we don't need to use ```std::move``` because compilers can use the technique called RVO.

http://stackoverflow.com/questions/17473753/c11-return-value-optimization-or-move

**Comment by beru** [comment] 2017-01-28 16:58
But it still creates a temporary vec_t instance during the operation.
```cpp
static void df(vec_t& d, const vec_t& y, const vec_t& t){ d.resize(t.size()); ...; }
```
I prefer this style since it may reduce the amount of work of heap manager.
Just my two cents.

**Comment by Randl** [comment] 2017-02-10 10:41
@liwangqian If you believe there are places you can introduce speedup, please send us PR with speed measurements

**Comment by Randl** [comment] 2017-04-14 06:49
Closing, if there are places with confirmed speedup, please send a PR

**Closed by Randl** 2017-04-14 06:49 UTC
Labels: contributions welcome, performance, Wait for reply
